"""Blog and BlogArtifact models."""
from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING
from uuid import UUID

from sqlalchemy import ForeignKey, Index, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.common.types import PipelineStatus, PipelineStep
from app.infrastructure.database.base import BaseModel

if TYPE_CHECKING:
    from app.domain.topics.models import Topic


class Blog(BaseModel):
    """
    Core blog entity.
    Tracks the source content, storage locations, and pipeline progression.
    """
    __tablename__ = "blogs"

    topic_id: Mapped[UUID] = mapped_column(ForeignKey("topics.id"), index=True)

    title: Mapped[str] = mapped_column(String(500))
    sequence_position: Mapped[int] = mapped_column(default=0)
    source_url: Mapped[str | None] = mapped_column(String(2000), default=None)
    source_text: Mapped[str] = mapped_column(Text)
    
    # State Machine 
    pipeline_status: Mapped[PipelineStatus] = mapped_column(
        String(50), default=PipelineStatus.DRAFT
    )
    
    generate_until_step: Mapped[PipelineStep] = mapped_column(
        String(100), default=PipelineStep.AUDIO_GENERATION
    )
    
    audio_file_path: Mapped[str | None] = mapped_column(String(1000), default=None)
    audio_duration_seconds: Mapped[int | None] = mapped_column(default=None)
    
    published_at: Mapped[datetime | None] = mapped_column(default=None)

    # Relationships 
    topic: Mapped[Topic] = relationship(back_populates="blogs")
    
    # Cascade ensures deleting a blog wipes out all its pipeline history.
    artifacts: Mapped[list[BlogArtifact]] = relationship(
        back_populates="blog",
        cascade="all, delete-orphan",
        order_by="BlogArtifact.created_at.desc()",
    )


class BlogArtifact(BaseModel):
    """
    Immutable pipeline outputs. 
    Stores the large text generated by the LLM for each specific step.
    """
    __tablename__ = "blog_artifacts"
    
    __table_args__ = (
        # Prevents accidental duplication of a version for a specific step
        UniqueConstraint("blog_id", "step_name", "version", name="uq_blog_artifact_version"),
        # Optimizes querying for the "active" pipeline state
        Index("ix_blog_artifact_current", "blog_id", "step_name", "is_current"),
    )

    blog_id: Mapped[UUID] = mapped_column(ForeignKey("blogs.id", ondelete="CASCADE"))
    
    # Which pipeline step generated this text? (e.g., ANALYSIS, SCRIPT)
    step_name: Mapped[PipelineStep] = mapped_column(String(100))
    version: Mapped[int] = mapped_column(default=1)
    
    # The generated text output
    content: Mapped[str] = mapped_column(Text)
    is_current: Mapped[bool] = mapped_column(default=True)

    # Relationships 
    blog: Mapped[Blog] = relationship(back_populates="artifacts")