[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "audio-blog-pipeline"
version = "0.1.0"
description = "An async pipeline to convert text blogs into high-quality audio blogs."
requires-python = ">=3.12"

dependencies = [
    "litestar>=2.12.0,<3.0.0",
    "litestar-granian>=0.2.0",
    "asyncpg>=0.30.0",
    "sqlalchemy[asyncio]>=2.0.40,<3.0.0",
    "advanced-alchemy>=0.30.0",
    "python-dotenv>=1.2.2",
    "groq>=1.1.1",
    "edge-tts>=7.2.7",
    "prometheus-client>=0.21.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-asyncio>=0.24.0",
    "ruff>=0.9.0",
]

[tool.ruff]
line-length = 90
target-version = "py312"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint]
select = [
    "F", 
    "E", 
    "W", 
    "I", 
    "B", 
    "UP", 
    "SIM", 
    "ASYNC", 
    "RUF", 
    "S", 
    "RET", 
    "TCH", 
    "PT", 
    "ARG", 
    "D"
]
ignore = [
    "E501",
    "D100",
    "D104",
    "D105",
    "D106",
    "D107"
]

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["app"] 

[tool.ruff.lint.pydocstyle]
convention = "google" 

[tool.ruff.lint.per-file-ignores]
"tests/**/*" = ["D", "S101", "S105"]
"scripts/**/*" = ["D"]

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.hatch.build.targets.wheel]
packages = ["src/app"]